#ifndef LANG_H
#define LANG_H

#include "objects.h"

class LanguageManager;
class IIniFile;

class Language : public IObject
{
public:
	explicit Language(LanguageManager *owner, std::string id, const std::string &file_name);
	~Language();
	std::string id() const { return id_; }
	std::string file_name() const { return file_name_; }
	std::string name() const { return name_; }
private:
	LanguageManager *owner_;
	std::string id_;
	std::string file_name_;
	std::string name_;
};

class LanguageManager : public ObjectList<Language>
{
public:
	explicit LanguageManager();
	Language *GetLanguageById(const std::string &id) const;
	static std::string default_language() { return "zh"; }
private:
};

enum LangString {
	lsAbout,
	lsActivationServerNotSpecified,
	lsAdd,
	lsAddFile,
	lsAddFolder,
	lsAddFunction,
	lsAdditional,
	lsAddress,
	lsAddressUsedByFunction,
	lsAllFiles,
	lsAssemblies,
	lsAutoSaveProject,
	lsBack,
	lsBlocked,
	lsBreakAddress,
	lsBuildDate,
	lsCalculator,
	lsCancel,
	lsCaseSensitive,
	lsChanging,
	lsClose,
	lsCode,
	lsContains,
	lsComments,
	lsCommandNotSupported,
	lsCompilationLog,
	lsCompilationType,
	lsCompilationTypeHelp,
	lsCompile,
	lsCompiled,
	lsCompiling,
	lsConfirmation,
	lsContents,
	lsContinue,
	lsCopy,
	lsCount,
	lsCPU,
	lsCreateFileError,
	lsCreateSegmentError,
	lsCustomerName,
	lsCustomerNameTooLong,
	lsCut,
	lsDate,
	lsDefault,
	lsDelete,
	lsDeleteFile,
	lsDeleteFolder,
	lsDeleteFunction,
	lsDeleteLicense,
	lsDeleteDefaultTemplate,
	lsDeleteTemplate,
	lsDeleting,
	lsDemoVersion,
	lsDetails,
	lsDetection,
	lsDirectories,
	lsDump,
	lsEdit,
	lsEmail,
	lsEmailTooLong,
	lsError,
	lsEthernet,
	lsExamples,
	lsExcludedFromCompilation,
	lsExcludedFromMemoryProtection,
	lsExcludedFromPacking,
	lsExecutableFiles,
	lsExecute,
	lsExit,
	lsExpirationDate,
	lsExport,
	lsExportKeyPair,
	lsExports,
	lsExternalAddress,
	lsFile,
	lsFileCanNotBePacked,
	lsFileCorrupted,
	lsFileHasIncorrectFormat,
	lsFileHasNoCodeSegment,
	lsFileHasUnknownFormat,
	lsFileHasUnsupportedProcessor,
	lsFileHasUnsupportedSubsystem,
	lsFileName,
	lsFileNameNotSpecified,
	lsFileNotFound,
	lsFiles,
	lsFlags,
	lsForward,
	lsFreeUpdatesPeriod,
	lsFunction,
	lsFunctionNotFound,
	lsFunctions,
	lsFunctionsForProtection,
	lsGenerate,
	lsGoTo,
	lsHardwareID,
	lsHDD,
	lsHelp,
	lsHomePage,
	lsHost,

	lsImport,
	lsImportLicense,
	lsImportLicenseFromSerialNumber,
	lsImportLicensesError,
	lsImportLicensesFromProjectFile,
	lsImportLicensesResult,
	lsImportProtection,
	lsImportProtectionHelp,
	lsImports,
	lsImportSerialNumberError,
	lsInformation,
	lsInstallCOMServer,

	lsInvalidHWID,
	lsInvalidParameterValue,
	lsInvalidProductCode,
	lsItems,
	lsJumpToInternalAddress,
	lsJumpToCommandPart,
	lsLanguage,
	lsLoadAtStart,
	lsLoading,
	lsLicensingParametersFile,
	lsLicensingParametersNotInitialized,
	lsMAPFileHasIncorrectTimeStamp,
	lsMarker,
	lsMarkerExists,
	lsMaxBuildDate,
	lsMemoryProtection,
	lsMemoryProtectionHelp,
	lsMessages,
	lsMinimalFunctionSize,
	lsModule,
	lsModuleNotSpecified,
	lsModulus,
	lsMutation,
	lsName,
	lsNext,
	lsNewTemplate,
	lsNo,
	lsNone,
	lsNotEnoughPlace,
	lsOK,
	lsOpen,
	lsOpenFileError,
	lsOpenModuleError,
	lsOperationCanceledByUser,
	lsOptionNotAvailable,
	lsOptions,
	lsOrderRef,
	lsOutputFile,
	lsOutputFileSize,
	lsOverwriteTemplate,
	lsPacking,
	lsPackOutputFile,
	lsPackOutputFileHelp,
	lsParameters,
	lsParametersForDelphi,
	lsParametersForMSVC,
	lsParametersForNET,
	lsParametersForPHP,
	lsPaste,
	lsPasteSerialNumber,
	lsLockToSerialNumber,
	lsPrevious,
	lsPrivateExp,
	lsProcess,
	lsProcessNotSpecified,
	lsProductCode,
	lsProject,
	lsProjectFile,
	lsProjectFiles,
	lsProtection,
	lsPublicExp,
	lsPurchaseLicense,
	lsPurchaseSubscription,
	lsQuickStart,
	lsRawAddress,
	lsRawSize,
	lsRecentFiles,
	lsRedo,
	lsReferences,
	lsRegisterCOMServer,
	lsRegisteredTo,
	lsRename,
	lsResourceProtection,
	lsResourceProtectionHelp,
	lsResources,
	lsRunningTimeLimit,
	lsSave,
	lsSaveFileError,
	lsSaveLicensesAs,
	lsSaveProject,
	lsSaveProjectAs,
	lsSaveTemplateAs,
	lsSaving,
	lsSerialNumberTooLong,
	lsSavingStartupCode,

	lsSearch,
	lsSearchInFile,
	lsSearching,
	lsSearchInModule,
	lsSearchResult,
	lsSearchResults,
	lsSearchWrapped,
	lsSegmentCanNotBePacked,
	lsSegment,
	lsSegments,
	lsSettings,
	lsSetup,
	lsShowProtectedFunctions,
	lsSize,
	lsStart,
	lsString,
	lsStripDebugInfo,
	lsStripRelocations,
	lsTemplates,
	lsTools,
	lsType,
	lsUltra,
	lsUndo,
	lsUnknown,
	lsUnregisteredVersion,
	lsUsage,
	lsUsageCount,
	lsUseOtherProject,
	lsUseTaggantSystem,
	lsUserData,
	lsUserDataTooLong,
	lsValue,
	lsVersion,
	lsVirtualization,
	lsVirtualizationTools,
	lsVirtualizationToolsFound,
	lsWarning,
	lsWatchedFileChange,
	lsWatermark,
	lsWatermarkIsDisabled,
	lsWatermarkNotFound,
	lsWelcome,
	lsYes,
	lszhucezhe,
	lsyouxiang,
	lsxukezheng,
	lsCNT
};


class LangStringList
{
public:
	LangStringList();
	void use_defaults();
	std::string operator[](LangString index) const;
private:

	std::string values_[lsCNT],	default_values_[lsCNT];
};

extern LangStringList language;

#endif